name: WoodConverter
main: com.ryebread761.woodconverter.Main
version: 1.1
author: ryebread761
softdepend: [Vault]
commands:
    woodconverter:
        description: Convert wood.
        usage: /woodconverter
        permission: woodconverter.woodconverter
        permisison-message: You don't have permission to do that!
        aliases: [wc]